@API_HostAddress = http://localhost:5296

GET {{API_HostAddress}}/weatherforecast/
Accept: application/json

###
POST {{API_HostAddress}}/Auth/register
Content-Type: application/json
{
  "firstName": "Abdelrahman",
  "lastName": "Mohammed",
  "email": "abdo@gmail.com",
  "password": "Password123!",
  "address": "Mansoura, Egypt"
}